### ISSUE TITLE
Missing repositories: multimodal_emg_private and simple_tracker

### ISSUE THREAD

**Issue by wuyd17** [hahnec/gulm#1]
<img width="608" alt="截屏2024-07-22 14 01 16" src="https://github.com/user-attachments/assets/738d19ad-c817-4ca9-85ec-0a89646daa7b">
I have recently been trying to learn and reproduce your GULM. However, I noticed that there are references to two repositories, "multimodal_emg_private" and "simple_tracker", which seem to be missing.

Could you please provide access to these repositories or let me know if there are any alternatives? Your assistance would be greatly appreciated.

**Comment by hahnec** [comment]
I have made [simple_tracker](https://github.com/hahnec/simple_tracker) public and updated the URL of [multimodal_emg](https://github.com/hahnec/multimodal_emg). My private version of *multimodal_emg* was actually behind the public one.

**Comment by wuyd17** [comment]
> I have made [simple_tracker](https://github.com/hahnec/simple_tracker) public and updated the URL of [multimodal_emg](https://github.com/hahnec/multimodal_emg). My private version of _multimodal_emg_ was actually behind the public one.

Thank you so much!
